|    nom   | prenom  | classe | groupe |
|----------|---------|--------|--------|
|  ZANINA  |  Sirine | 2LM1   | TP2    |


# TP1 Probabilité et statistique
<html>
   <head>
      <title>HTML Base Tag Example</title>
      <base href = "https://github.com/nevermind78/Proba_stat_4_LM" />
   </head>
   <body>
      <img src = "https://th.bing.com/th/id/OIP.Quijt6_GuJ-OzuMSNQ_S1gHaHa?pid=Api&rs=1" width="200" alt = "Logo Image"/>
    </body>

</html>


In [3]:
from __future__ import print_function
import numpy as np
import pandas as pd
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

In [4]:
np.__version__

'1.23.3'

## Probabilités - approche fréquentiste
### Définition par la fréquence relative :
* une expérience d’ensemble fondamental  est exécutée plusieurs fois sous les mêmes conditions.
* Pour chaque événement E de , n(E) est le nombre de fois où l’événement E survient lors des n premières répétitions de l’expérience.
* **`P(E)`**, la probabilité de l’événement E est définie de la manière suivante :

$$P(E)=\lim_{n\to\infty}\dfrac{n(E)}{n} $$ 

## Simulation d'un dé parfait

In [3]:
# seed the random number generator
np.random.seed(1)

# Example: sampling 
#
# do not forget that Python arrays are zero-indexed,
# and the 2nd argument to NumPy arange must be incremented by 1
# if you want to include that value
n = 6 # les 6 faces du dé
k = 200000 # Nombre de répétition de l'éxpériance

T=np.random.choice(np.arange(1, n+1), k, replace=True)
print(T)
unique, counts = np.unique(T, return_counts=True)
print(unique,counts)
dic=dict(zip(unique, counts))
print(dic)
df=pd.DataFrame(list(dic.items()),columns=['i','Occurence'])
df.set_index(['i'], inplace=True)
df['Freq']=df['Occurence']/k
df['P({i})']='{}'.format(1/6)
df

[6 4 5 ... 6 5 2]
[1 2 3 4 5 6] [33346 33221 33447 33224 33379 33383]
{1: 33346, 2: 33221, 3: 33447, 4: 33224, 5: 33379, 6: 33383}


Occurence      Freq               P({i})
i                                          
1      33346  0.166730  0.16666666666666666
2      33221  0.166105  0.16666666666666666
3      33447  0.167235  0.16666666666666666
4      33224  0.166120  0.16666666666666666
5      33379  0.166895  0.16666666666666666
6      33383  0.166915  0.16666666666666666

In [4]:
# creation d'une liste L.
L=[1,2,3]

# creation d'une liste M.
M=['a','b','c']
# la fonction zip(l1, l2) prend en parametre deux listes et retourne une serie de tuples 
# qui contient le premier element dans la premiere liste combiné avec le premier 
# element de la deuxieme liste, etc.
# puis le result est transformer en une list grâce à la fonction list().
list(zip(L,M))

[(1, 'a'), (2, 'b'), (3, 'c')]

## Ajouter de l'intéraction 

In [13]:
# On a définit une fonction qui simule le lancement d'un dé nommée dice_sim qui prend comme paramètre la variable k avec une valeur de 100.
# k représente le nombre de fois qu'on va simulé le dé.

def dice_sim(k=100):
    n = 6    
    T=np.random.choice(np.arange(1, n+1), k, replace=True)
    # np = une abbréviation souvent utilisé pour NumPy
    # np.arrange(1, n+1) => (1, n+1) représente l'intervalle des valeurs qu'on va instancé.
    # np.arrange(1, n+1), n=6 => np.arrange(1, 7) => [1, 2, 3, 4, 5, 6]
    # k représente le nombre de fois qu'on va simulé le dé.
    # replace = True => autoriser la répétition => tirage simultané avec remise => le tableau np.arrange(1, n+1)
    # qui crée une instance de ndarray et retourne une référence de lui reste le même tout au long de simulation.

    # T: un ndarray contenant les valeurs obtenues aprés chaque lancé.
    # np.random.choice génère une valeur aléatoirement d'un tableau 1D de type ndarray.

    unique, counts = np.unique(T, return_counts=True)
    # return_counts = True => retourne l'occurence de chaque element dans le tableau T et le sauvegarde 
    # dans la variable counts sous la forme d'un tableau de type NDArray.
    # unique: contient les éléments dans le tableau T sans repetition, le type du tableau unique est NDArray.
    
    dic=dict(zip(unique, counts))
    # la variable dic de type dictionnaire prend en paramètre la fonction zip(unique, counts) qui retourne une série des tuples contenant le premier élément dans le tableau unique avec le 1er élément dans le tableau counts, etc.
    # => dic est un disctionnaire qui a comme des clés les série des tuples générés par la fonction zip.
    df=pd.DataFrame(list(dic.items()),columns=['i','Occurence'])
    # pd : abbréviation souvent utilisé pour la bibliothèque pandas.
    # df: un DataFrame object ayant comme colonnes: "i" et "occurence" et comme lignes les valeurs dans list(dic.items())
    # list(dic.item()) =>  dic.item() est une méthode qui retourne un objet qui affiche une list de chaque clé avec sa valeur d'un dictionnaire en une série des tuples couples.
    df.set_index(['i'], inplace=True)
    # df.set_index => set the index of a DataFrame as "i"
    # inplace = true => fait les changements dans le DataFrame si vrai.
    df['Freq']=df['Occurence']/k
    # on a ajouté une colonne nommée "Freq" qui prend comme des valeurs la valeur de "occurence" divisé par k: le nombre de fois qu'on a jeté le dé.
    df['P({i})']='{0:.3f}'.format(1/6)
    # On a ajouté la colonne P(i) qui a comme valeur la probabilité d'obtenir un nombre aléatoire compris entre 1 et 6 qui est : 1/6
    # '{0:.3f}'.format : on a spécifié 3 chiffres aprés la virgule et "f" représent le type de variable "float".

    return df
    # retourner le DataFrame df.
    

In [14]:
dice_sim(100)
# simulation de la jeté d'un dé 100 fois.

Occurence  Freq P({i})
i                        
1         19  0.19  0.167
2         16  0.16  0.167
3         17  0.17  0.167
4         15  0.15  0.167
5         15  0.15  0.167
6         18  0.18  0.167

In [15]:
interact(dice_sim,k=widgets.IntSlider(min=1000, max=50000, step=500, value=10));
# la fonction interact crée automatiquement une interface pour l'utilisateur(UI) pour explorer le code et 
# la data d'une manière intéractive.
# windgets.IntSlider => crée un slider entre les valeurs 1000 et 50000, avec un step de 500 entre les valeurs
# et un nombre des valeurs qui est 10( value = 10).

interactive(children=(IntSlider(value=1000, description='k', max=50000, min=1000, step=500), Output()), _dom_c…

## Cas d'un dé truqué

In [6]:
p=[0.1, 0.1, 0.1, 0.1,0.1,0.5]
# p: liste des probabilités d'un cas d'un dé truque.
sum(p)
# donne la somme des éléments trouvés en p.

1.0

In [1]:
def dice_sim(k=100,q=[[0.1, 0.1, 0.1, 0.1,0.1,0.5],[0.2, 0.1, 0.2, 0.1,0.1,0.3]]):
    # une fonction qui simule le lancement d'un dé  nomée dice_sim 
    # qui prend k et q comme deux parametres optionales avec k 
    # initialiser à 100 et q initialiser à [[0.1, 0.1, 0.1, 0.1,0.1,0.5], [0.2, 0.1, 0.2, 0.1,0.1,0.3]] .
    n = 6
    qq=q
    T=np.random.choice(np.arange(1, n+1), k, replace=True,p=qq)
    unique, counts = np.unique(T, return_counts=True)
    dic=dict(zip(unique, counts))
    df=pd.DataFrame(list(dic.items()),columns=['i','Occurence'])
    df.set_index(['i'], inplace=True)
    df['Freq']=df['Occurence']/k
    df['P({i})']=['{0:.3f}'.format(j) for j in q]
    return df

In [5]:
interact(dice_sim,k=widgets.IntSlider(min=1000, max=50000, step=500, value=10));

interactive(children=(IntSlider(value=1000, description='k', max=50000, min=1000, step=500), Dropdown(descript…

## Exercice 1: 

Tester l'intéraction précédente pour plusieurs valeurs de `q`
Donner votre conclusion :

In [9]:
# Conclusion 
# Sur cette nouvelle simulation comportant plus d'expériences, on remarque que les fréquences et les occurences 
# sont d'avatange regroupées autour des plus grandes valeurs de probabilité.


## Permutation Aléatoire

In [6]:
np.random.seed(2)

m = 1
n = 10

v = np.arange(m, n+1)
print('v =', v)

np.random.shuffle(v)
print('v, shuffled =', v)

v = [ 1  2  3  4  5  6  7  8  9 10]
v, shuffled = [ 5  2  6  1  8  3  4  7 10  9]


## Exercice 2
Vérifier que les permutation aléatoires sont uniforme , c'est à dire que la probabilité de générer une permutation d'élement de {1,2,3} est 1/6.
En effet les permutations de {1,2,3} sont :
* 1 2 3
* 1 3 2
* 2 1 3
* 2 3 1
* 3 1 2
* 3 2 1


In [7]:
k =10
m = 1
n = 3
v = np.arange(m, n+1)
T=[]
for i in range(k):
    np.random.shuffle(v)
    w=np.copy(v)
    T.append(w)

In [12]:
TT=[str(i) for i in  T]
TT

['[1 3 2]',
 '[3 1 2]',
 '[1 2 3]',
 '[1 3 2]',
 '[3 1 2]',
 '[3 1 2]',
 '[1 3 2]',
 '[2 1 3]',
 '[3 1 2]',
 '[2 3 1]']

In [8]:
k =1000
m = 1
n = 3
v = np.arange(m, n+1)
T=[]
for i in range(k):
    np.random.shuffle(v)
    w=np.copy(v)
    T.append(w)

TT=[str(i) for i in  T]
unique, counts = np.unique(TT, return_counts=True)
dic=dict(zip(unique, counts))
df=pd.DataFrame(list(dic.items()),columns=['i','Occurence'])
df.set_index(['i'], inplace=True)
df['Freq']=df['Occurence']/k
df['P({i,j,k})']='{0:.3f}'.format(1/6)
df

Occurence   Freq P({i,j,k})
i                                   
[1 2 3]        169  0.169      0.167
[1 3 2]        180  0.180      0.167
[2 1 3]        161  0.161      0.167
[2 3 1]        169  0.169      0.167
[3 1 2]        157  0.157      0.167
[3 2 1]        164  0.164      0.167

### Donner  votre conclusion en expliquant le script 

In [14]:
# Explication 

# The universality of a the uniform distribution:










## Probabilité conditionnelle 

Rappelons que l'interprétation fréquentiste de la probabilité conditionnelle basée sur un grand nombre `n` de répétitions d'une expérience est $ P (A | B) ≈ n_ {AB} / n_ {B} $, où $ n_ {AB} $ est le nombre de fois où $ A \cap B $ se produit et $ n_ {B} $ est le nombre de fois où $ B $ se produit. Essayons cela par simulation et vérifions les résultats de l'exemple 2.2.5. Utilisons donc [`numpy.random.choice`] (https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.choice.html) pour simuler les familles` n`, chacun avec deux enfants.


In [15]:
np.random.seed(34)

n = 10**5
child1 = np.random.choice([1,2], n, replace=True) 
child2 = np.random.choice([1,2], n, replace=True) 

print('child1:\n{}\n'.format(child1))

print('child2:\n{}\n'.format(child2))

child1:
[2 1 1 ... 1 2 1]

child2:
[2 2 2 ... 2 2 1]



Ici, «child1» est un «tableau NumPy» de longueur «n», où chaque élément est un 1 ou un 2. En laissant 1 pour «fille» et 2 pour «garçon», ce «tableau» représente le sexe du enfant aîné dans chacune des familles «n». De même, «enfant2» représente le sexe du plus jeune enfant de chaque famille.


In [16]:
np.random.choice(["girl", "boy"], n, replace=True)

array(['boy', 'boy', 'boy', ..., 'boy', 'boy', 'boy'], dtype='<U4')

mais il est plus pratique de travailler avec des valeurs numériques.

Soit $ A $ l'événement où les deux enfants sont des filles et $ B $ l'événement où l'aîné est une fille. Suivant l'interprétation fréquentiste, nous comptons le nombre de répétitions où $ B $ s'est produit et le nommons `n_b`, et nous comptons également le nombre de répétitions où $ A \cap B $ s'est produit et le nommons` n_ab`. Enfin, nous divisons `n_ab` par` n_b` pour approximer $ P (A | B) $.

In [17]:
n_b = np.sum(child1==1)
n_ab = np.sum((child1==1) & (child2==1))

print('P(both girls | elder is girl) = {:0.2F}'.format(n_ab / n_b))

P(both girls | elder is girl) = 0.50


L'esperluette `&` est un élément par élément $ AND $, donc `n_ab` est le nombre de familles où le premier et le deuxième enfant sont des filles. Lorsque nous avons exécuté ce code, nous avons obtenu 0,50, confirmant notre réponse $ P (\text {les deux filles | l'aîné est une fille}) = 1/2 $.

Soit maintenant $ A $ l'événement où les deux enfants sont des filles et $ B $ l'événement selon lequel au moins l'un des enfants est une fille. Alors $ A \cap B $ est le même, mais `n_b` doit compter le nombre de familles où au moins un enfant est une fille. Ceci est accompli avec l'opérateur élémentaire $ OR $ `|` (ce n'est pas une barre de conditionnement; c'est un $ OR $ inclusif, retournant `True` si au moins un élément est` True`).

In [18]:
n_b = np.sum((child1==1) | (child2==2))
n_ab = np.sum((child1==1) & (child2==1))

print('P(both girls | at least one girl) = {:0.2F}'.format(n_ab / n_b))

P(both girls | at least one girl) = 0.33


Pour nous, le résultat était de 0,33, confirmant que $ P (\text {les deux filles | au moins une fille}) = 1/3 $.

HR |O2Sat|Temp|...|HospAdmTime|ICULOS|SepsisLabel
---|---|---|---|---|---|---|
NaN|  NaN| NaN|...|        -50|     1|          0
 86|   98| NaN|...|        -50|     2|          0
 75|  NaN| NaN|...|        -50|     3|          1
 99|  100|35.5|...|        -50|     4|          1

<h1> Titre </h1>

# Titre

<h2> Sous Titre </h2>

## sous titre



<p> ezrezknvzclknznvvzvsfvsjbv
    vzobvozijbvoizjbvoiuzbvojdzv
    vcbzihd ihsd isd 
    ezrezknvzclknznvvzvsfvsjbv
    vzobvozijbvoizjbvoiuzbvojdzv
    vcbzihd ihsd isd  ezrezknvzclknznvvzvsfvsjbv
    vzobvozijbvoizjbvoiuzbvojdzv
    vcbzihd ihsd isd ezrezknvzclknznvvzvsfvsjbv
    vzobvozijbvoizjbvoiuzbvojdzv
    vcbzihd ihsd isd
    </p>
    
## HtML    
<table>  
<tr><th>Nom</th><th>Prénom</th><th>Marks</th></tr>  
<tr><td>Sonoo</td><td>Jaiswal</td><td>60</td></tr>  
<tr><td>James</td><td>William</td><td>80</td></tr>  
<tr><td>Swati</td><td>Sironi</td><td>82</td></tr>  
<tr><td>Chetna</td><td>Singh</td><td>72</td></tr>  
</table>
    
## MD

  
Nom|Prénom|Marks
---|---|---
Sonoo|Jaiswal|60  
James|William|80 
Swati|Sironi|82  
Chetna|Singh|72

## Latex
`$$\sum_{k=1}^{\infty} \frac{1}{n^2}= \frac{\pi^2}{6}$$`

$$ \sum_{k=1}^{\infty} \frac{1}{n^2}= \frac{\pi^2}{6}$$
